// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonShop.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - CommonShopRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface CommonShopRoot : GPBRootObject
@end

#pragma mark - ChatMsg

typedef GPB_ENUM(ChatMsg_FieldNumber) {
  ChatMsg_FieldNumber_Talker = 1,
  ChatMsg_FieldNumber_Content = 2,
  ChatMsg_FieldNumber_MsgType = 3,
  ChatMsg_FieldNumber_ReceiveWxId = 4,
  ChatMsg_FieldNumber_ThImgVideo = 5,
  ChatMsg_FieldNumber_Videolength = 6,
  ChatMsg_FieldNumber_CreateTime = 7,
};

/// 消息实体
@interface ChatMsg : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *talker;
/// Test to see if @c talker has been set.
@property(nonatomic, readwrite) BOOL hasTalker;

@property(nonatomic, readwrite, copy, null_resettable) NSString *content;
/// Test to see if @c content has been set.
@property(nonatomic, readwrite) BOOL hasContent;

/// 必传 1:文本消息. 2:图片URL 3：视频URL 4：语音URL 5：名片 6:文章 7:位置 8:红包
@property(nonatomic, readwrite) int32_t msgType;

@property(nonatomic, readwrite) BOOL hasMsgType;
@property(nonatomic, readwrite, copy, null_resettable) NSString *receiveWxId;
/// Test to see if @c receiveWxId has been set.
@property(nonatomic, readwrite) BOOL hasReceiveWxId;

/// 视频第一帧图片地址
@property(nonatomic, readwrite, copy, null_resettable) NSString *thImgVideo;
/// Test to see if @c thImgVideo has been set.
@property(nonatomic, readwrite) BOOL hasThImgVideo;

/// 视频时长，单位秒
@property(nonatomic, readwrite) int32_t videolength;

@property(nonatomic, readwrite) BOOL hasVideolength;
@property(nonatomic, readwrite) int64_t createTime;

@property(nonatomic, readwrite) BOOL hasCreateTime;
@end

#pragma mark - Identity

typedef GPB_ENUM(Identity_FieldNumber) {
  Identity_FieldNumber_ShopId = 1,
  Identity_FieldNumber_UserId = 2,
  Identity_FieldNumber_Token = 3,
};

@interface Identity : GPBMessage

@property(nonatomic, readwrite) int32_t shopId;

@property(nonatomic, readwrite) BOOL hasShopId;
@property(nonatomic, readwrite) int32_t userId;

@property(nonatomic, readwrite) BOOL hasUserId;
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;
/// Test to see if @c token has been set.
@property(nonatomic, readwrite) BOOL hasToken;

@end

#pragma mark - Operation

typedef GPB_ENUM(Operation_FieldNumber) {
  Operation_FieldNumber_Cmd = 1,
  Operation_FieldNumber_Data_p = 2,
};

@interface Operation : GPBMessage

/// 必传. 具体业务指令 如发朋友圈，加好友，点赞等
@property(nonatomic, readwrite) int32_t cmd;

@property(nonatomic, readwrite) BOOL hasCmd;
/// 必传. 以JOSN格式编写具体数据
@property(nonatomic, readwrite, copy, null_resettable) NSString *data_p;
/// Test to see if @c data_p has been set.
@property(nonatomic, readwrite) BOOL hasData_p;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
